module.exports={
    "/suretyonline/api/v1/admin": [
        "role_approval",
        "role_principal",
        "role_data_entry",
        "role_marketing",
        "role_div_bisnis",
        "role_testing",
        "role_admin",
        "role_agen",
        "role_analis",
        "role_checker_maker"
    ],
    "/suretyonline/api/v1/master": ["role_approval",
        "role_principal",
        "role_data_entry",
        "role_marketing",
        "role_div_bisnis",
        "role_testing",
        "role_admin",
        "role_agen",
        "role_analis",
        "role_checker_maker"],
    "/suretyonline/api/v1/approval": ["role_approval",
        "role_principal",
        "role_data_entry",
        "role_marketing",
        "role_div_bisnis",
        "role_testing",
        "role_admin",
        "role_agen",
        "role_analis",
        "role_checker_maker"],
    "/suretyonline/api/v1": ["role_approval",
        "role_principal",
        "role_data_entry",
        "role_marketing",
        "role_div_bisnis",
        "role_testing",
        "role_admin",
        "role_agen",
        "role_analis",
        "role_checker_maker"],
    "/suretyonline/api/v1/akseptasi": ["role_approval",
        "role_principal",
        "role_data_entry",
        "role_marketing",
        "role_div_bisnis",
        "role_testing",
        "role_admin",
        "role_agen",
        "role_analis",
        "role_checker_maker"]
    }
    